server:
  port: 8080

balancer:
  algorithm: "carbon-aware" 
  api_key: "CHIAVE_DA_INSEIRE" # chiave per accedere all'API di carbon-aware

nodes:
  - url: "http://worker1:9001"
    zone: "SE" # Svezia
  - url: "http://worker2:9002"
    zone: "DE" # Germania
  - url: "http://worker3:9003"
    zone: "US-TX" # Texas