server:
  port: 8080

balancer:
  algorithm: "carbon-aware"  
  api_base_url: "https://api.electricitymap.org" # URL base per API 

nodes:
  - url: "http://worker1:9001"
    zone: "SE" # Svezia
  - url: "http://worker2:9002"
    zone: "DE" # Germania
  - url: "http://worker3:9003"
    zone: "US-TEX-ERCO" # Texas