FROM golang:alpine
WORKDIR /app

COPY go.mod ./
RUN go mod download || true

COPY . .

# Compilazione del Worker
RUN go build -o worker worker/main.go

# Porta passata come parametro dal docker-compose
ENTRYPOINT ["./worker-app"] 